spring:
  application:
    name: villarosa
  security.user:
    name: test
    roles: USER
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 9098


datasource:
  jdbcUrl: jdbc:mariadb://localhost/villarosa
  minimumIdle: 1
  maximumPoolSize: 5
